services:
  mongodb:
    image: mongo:6.0.4
    container_name: mongodb
    mem_limit: 512m
    environment:
      - MONGO_INITDB_DATABASE=cargodb # Nome del database da inizializzare
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - iss-network

  wenv:
    container_name: wenv
    image: docker.io/natbodocker/virtualrobotdisi25:2.2
    ports:
      - 8090:8090
      - 8091:8091/tcp
      - 8091:8091/udp
    networks:
      - iss-network

  basicrobot24:
    container_name: basicrobot24
    image: pretty2/basicrobot:2.13
    mem_limit: 512m
    ports:
      - 8020:8020/udp
      - 8020:8020/tcp
      - 8085:8085
    environment:
      - VIRTUAL_ENV=wenv
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
      - SERVICE_HOST=172.31.64.1
      - SERVICE_IP=172.31.64.1
      - MQTTBROKER=mosquittoalone
    depends_on:
      - wenv
      - eureka
      - mosquitto
    networks:
      - iss-network

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquittoalone
    environment:
      - MQTT_ALLOW_ANONYMOUS=true
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iss-network

  eureka:
    image: natbodocker/springcloud-eureka
    container_name: eurekaserver
    ports:
      - 8761:8761
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=60
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=120
    networks:
      - iss-network

  cargoserviceqak:
    container_name: cargoserviceqak 
    image: docker.io/natbodocker/cargoserviceqak:1.0
    environment:
      - MONGO_HOST=mongodb
      - SERVICE_IP=192.168.1.189
    ports:
      - 8111:8111/tcp
      - 8111:8111/udp
    networks:
      - iss-network
    depends_on:
      mongodb:
        condition: service_started
      eureka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka:8761/eureka/apps/CTXCARGOSERVICE"] # Assicurati che 'CARGOSERVICEQAK' sia il nome corretto
      interval: 10s
      timeout: 10s
      retries: 12

networks:
  iss-network:
    external: true