/* Generated by AN DISI Unibo */ 
package it.unibo.companyrequestreceiver

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Companyrequestreceiver ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val Errormsg = "\"the system is occupied with another request\""
				val Msg = "\"the system is taking care of your request\""
				var PID = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name STARTS")
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outblue("$name waiting to receive a request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t028",targetState="handleRequest",cond=whenRequest("sendrequest"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("sendrequest(PID)"), Term.createTerm("sendrequest(PID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								  				PID = payloadArg(0) 
								answer("sendrequest", "sendrequestAnswer", "sendrequestAnswerToRequest($Msg)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="forwardRequest", cond=doswitch() )
				}	 
				state("forwardRequest") { //this:State
					action { //it:State
						CommUtils.outblue("$name sending cargoservice the request")
						request("loadrequest", "loadrequest($PID)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="occupiedWaiting", cond=doswitch() )
				}	 
				state("occupiedWaiting") { //this:State
					action { //it:State
						CommUtils.outblue("$name is waiting for the system to free itself ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t129",targetState="rejectRequest",cond=whenRequest("sendrequest"))
					transition(edgeName="t130",targetState="waiting",cond=whenReply("resultrequest"))
				}	 
				state("rejectRequest") { //this:State
					action { //it:State
						CommUtils.outblue("$name rejecting request")
						answer("sendrequest", "sendrequestAnswer", "sendrequestAnswer($Errormsg)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="occupiedWaiting", cond=doswitch() )
				}	 
			}
		}
} 
