/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				val StepTime = 350
				val HomeX = 0
				val HomeY = 0 
				val IoX = 5
				val IoY = 0
		
				var DestSlotX = 0
				var DestSlotY = 0
				var CurrentDestX = 0
				var CurrentDestY = 0
				
		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name RUNNING")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engageRobot", cond=doswitch() )
				}	 
				state("engageRobot") { //this:State
					action { //it:State
						CommUtils.outblack("Engaging basic-robot...")
						request("engage", "engage(cargorobot,$StepTime)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="waitForCommand",cond=whenReply("engagedone"))
					transition(edgeName="t07",targetState="retryEngage",cond=whenReply("engagerefused"))
				}	 
				state("retryEngage") { //this:State
					action { //it:State
						CommUtils.outblack("Engage refused, retrying...")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engageRobot", cond=doswitch() )
				}	 
				state("waitForCommand") { //this:State
					action { //it:State
						CommUtils.outblack("Waiting for command")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t18",targetState="prepareDelivery",cond=whenDispatch("command"))
				}	 
				state("prepareDelivery") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("command(C)"), Term.createTerm("command(C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val C = payloadArg(0).toString()
												val coords = C.split(" ").last().replace("(", "").replace(")", "").split(",")
												DestSlotX = coords[0].toInt()
												DestSlotY = coords[1].toInt()
												
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="pickup", cond=doswitch() )
				}	 
				state("pickup") { //this:State
					action { //it:State
						CommUtils.outblack("Going to IOPort to pick up product...")
						
						        	CurrentDestX = IoX
						        	CurrentDestY = IoY
						request("moverobot", "moverobot($CurrentDestX,$CurrentDestY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t29",targetState="delivery",cond=whenReply("moverobotdone"))
					transition(edgeName="t210",targetState="handleFailure",cond=whenReply("moverobotfailed"))
					interrupthandle(edgeName="t211",targetState="handleAnomaly",cond=whenEvent("alarm"),interruptedStateTransitions)
					interrupthandle(edgeName="t212",targetState="handleAnomaly",cond=whenEvent("anomalyDetected"),interruptedStateTransitions)
				}	 
				state("delivery") { //this:State
					action { //it:State
						CommUtils.outblack("Delivering product to slot...")
						
						        		CurrentDestX = DestSlotX
						        		CurrentDestY = DestSlotY
						request("moverobot", "moverobot($CurrentDestX,$CurrentDestY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t313",targetState="return",cond=whenReply("moverobotdone"))
					transition(edgeName="t314",targetState="handleFailure",cond=whenReply("moverobotfailed"))
					interrupthandle(edgeName="t315",targetState="handleAnomaly",cond=whenEvent("alarm"),interruptedStateTransitions)
					interrupthandle(edgeName="t316",targetState="handleAnomaly",cond=whenEvent("anomalyDetected"),interruptedStateTransitions)
				}	 
				state("return") { //this:State
					action { //it:State
						CommUtils.outblack("Returning to home position...")
						
						        		CurrentDestX = HomeX
						        		CurrentDestY = HomeY
						request("moverobot", "moverobot($CurrentDestX,$CurrentDestY)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t417",targetState="endOfTask",cond=whenReply("moverobotdone"))
					transition(edgeName="t418",targetState="handleFailure",cond=whenReply("moverobotfailed"))
					interrupthandle(edgeName="t419",targetState="handleAnomaly",cond=whenEvent("alarm"),interruptedStateTransitions)
					interrupthandle(edgeName="t420",targetState="handleAnomaly",cond=whenEvent("anomalyDetected"),interruptedStateTransitions)
				}	 
				state("endOfTask") { //this:State
					action { //it:State
						CommUtils.outblack("Transport complete. Emitting finishedtransport.")
						emit("finishedtransport", "finishedtransport(ok)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t521",targetState="handleFailure",cond=whenReply("moverobotfailed"))
					interrupthandle(edgeName="t522",targetState="handleAnomaly",cond=whenEvent("alarm"),interruptedStateTransitions)
					interrupthandle(edgeName="t523",targetState="handleAnomaly",cond=whenEvent("anomalyDetected"),interruptedStateTransitions)
				}	 
				state("handleFailure") { //this:State
					action { //it:State
						CommUtils.outred("Robot move failed. Check system status.")
						emit("finishedtransport", "finishedtransport(failure)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForCommand", cond=doswitch() )
				}	 
				state("handleAnomaly") { //this:State
					action { //it:State
						CommUtils.outblack("Anomaly detected. Stopping robot...")
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitFix", cond=doswitch() )
				}	 
				state("waitFix") { //this:State
					action { //it:State
						CommUtils.outblack("Waiting for anomaly to be fixed...")
						delay(200) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t524",targetState="resuming",cond=whenEvent("anomalyFixed"))
				}	 
				state("resuming") { //this:State
					action { //it:State
						request("moverobot", "moverobot($CurrentDestX,$CurrentDestY)" ,"basicrobot" )  
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
